import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'java-conventions'
    id 'junit5-conventions'
    id 'org.springframework.boot'
}

dependencies {
    // Imports Spring Boot Maven BOM
    implementation platform(SpringBootPlugin.BOM_COORDINATES)

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'

    implementation project(':alerting-system:model')
    implementation project(':alerting-system:alert-db')
    implementation project(':common-libs:common-model')

    annotationProcessor libs.lombok
    compileOnly libs.lombok

    implementation libs.springDocWebmvc

    implementation 'io.micrometer:micrometer-registry-prometheus'

    runtimeOnly 'org.postgresql:postgresql'

    implementation project(':common-libs:location-utils')

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation libs.junit.jupiter

    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    testImplementation project(':alerting-system:client')
    testImplementation project(':common-libs:test-extensions')
    testRuntimeOnly 'javax.xml.bind:jaxb-api:2.3.1'
}
