import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'java-conventions'
    id 'junit5-conventions'
    id 'org.springframework.boot'
}

dependencies {
    // Imports Spring Boot Maven BOM
    implementation platform(SpringBootPlugin.BOM_COORDINATES)

    implementation libs.jakartaWsApi

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    annotationProcessor 'org.projectlombok:lombok:1.18.38'
    compileOnly 'org.projectlombok:lombok:1.18.38'

    // Todo try to remove it with api in gradle
    implementation project(':alerting-system:model')

    implementation libs.guava
    implementation libs.springDocWebmvc

    implementation 'io.micrometer:micrometer-registry-prometheus'

    runtimeOnly 'org.postgresql:postgresql'

    implementation project(':logs-proto:camera:proto')
    implementation project(':alerting-system:protobuf')
    implementation project(':common-libs:location-utils')
    implementation("org.flywaydb:flyway-core")
    implementation("org.flywaydb:flyway-database-postgresql")

    implementation libs.parallelconsumer

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'

    testCompileOnly 'org.projectlombok:lombok:1.18.32'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'

    testImplementation libs.testcontainersKafka
    testImplementation project(':common-libs:test-extensions')
    testImplementation project(':logs-proto:camera:proto')
    testImplementation libs.testcontainersJupiter
}

bootJar {
    enabled = false
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += '-Xlint:-processing'
}