replicaCount: 3

image:
  tag: "1.0.0"

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 192Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: app.pathlens.io
  tls:
    - secretName: app-pathlens-io-tls
      hosts:
        - app.pathlens.io

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 8
