---
db_password: "{{ vault_db_password }}"

services:
  - name: pathlens-infra
    set_image_tag: false
    secret_values:
      - {value: "postgresql.auth.password={{ db_password }}", value_type: string}
      - {value: "postgresql.auth.postgresPassword={{ vault_postgres_admin_password }}", value_type: string}
  - name: device-rest
    secret_values:
      - {value: "database.password={{ db_password }}", value_type: string}
  - name: alerting-rest
    secret_values:
      - {value: "database.password={{ db_password }}", value_type: string}
  - name: alerting-evaluator
    secret_values:
      - {value: "config.postgresConfig.password={{ db_password }}", value_type: string}
  - {name: processor, secret_values: []}
  - {name: simulator, secret_values: []}
  - {name: frontend, secret_values: []}
