CREATE TABLE locations (
    site_id varchar(255) NOT NULL,
    country varchar(255),
    city varchar(255),
    latitude double precision,
    longitude double precision,
    CONSTRAINT pk_locations PRIMARY KEY (site_id)
);

CREATE TABLE device (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    serial_number varchar(255) NOT NULL,
    device_type varchar(50),
    status varchar(50),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    site_id varchar(255) NOT NULL,
    CONSTRAINT pk_device PRIMARY KEY (id),
    CONSTRAINT uk_device_serial_number UNIQUE (serial_number),
    CONSTRAINT fk_device_location FOREIGN KEY (site_id) REFERENCES locations (site_id)
);
