apiVersion: v2
name: alerting-rest
description: PathLens Alerting REST API (rules, notifications, target-log)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: pathlens-common
    version: 0.1.0
    repository: "file://../pathlens-common"
