apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pathlens.fullname" . }}
  labels:
    {{- include "pathlens.labels" . | nindent 4 }}
data:
  application.yml: |
    {{- $config := merge (dict "prometheusPortNumber" (.Values.metrics.port | int)) (deepCopy .Values.config) }}
    {{- toYaml $config | nindent 4 }}
