// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/proto/taxiLocation.proto
// Protobuf Java Version: 4.31.1

package org.shazaei.protobuf;

@com.google.protobuf.Generated
public final class TaxiLoc {
  private TaxiLoc() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      TaxiLoc.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaxiLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.TaxiLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string taxi_id = 1;</code>
     * @return Whether the taxiId field is set.
     */
    boolean hasTaxiId();
    /**
     * <code>required string taxi_id = 1;</code>
     * @return The taxiId.
     */
    java.lang.String getTaxiId();
    /**
     * <code>required string taxi_id = 1;</code>
     * @return The bytes for taxiId.
     */
    com.google.protobuf.ByteString
        getTaxiIdBytes();

    /**
     * <code>required string trip_id = 2;</code>
     * @return Whether the tripId field is set.
     */
    boolean hasTripId();
    /**
     * <code>required string trip_id = 2;</code>
     * @return The tripId.
     */
    java.lang.String getTripId();
    /**
     * <code>required string trip_id = 2;</code>
     * @return The bytes for tripId.
     */
    com.google.protobuf.ByteString
        getTripIdBytes();

    /**
     * <code>required double latitude = 3;</code>
     * @return Whether the latitude field is set.
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 3;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>required double longitude = 4;</code>
     * @return Whether the longitude field is set.
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 4;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>required int64 timestamp = 7;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code protobuf.TaxiLocation}
   */
  public static final class TaxiLocation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.TaxiLocation)
      TaxiLocationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        TaxiLocation.class.getName());
    }
    // Use TaxiLocation.newBuilder() to construct.
    private TaxiLocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TaxiLocation() {
      taxiId_ = "";
      tripId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.shazaei.protobuf.TaxiLoc.internal_static_protobuf_TaxiLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.shazaei.protobuf.TaxiLoc.internal_static_protobuf_TaxiLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.shazaei.protobuf.TaxiLoc.TaxiLocation.class, org.shazaei.protobuf.TaxiLoc.TaxiLocation.Builder.class);
    }

    private int bitField0_;
    public static final int TAXI_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object taxiId_ = "";
    /**
     * <code>required string taxi_id = 1;</code>
     * @return Whether the taxiId field is set.
     */
    @java.lang.Override
    public boolean hasTaxiId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string taxi_id = 1;</code>
     * @return The taxiId.
     */
    @java.lang.Override
    public java.lang.String getTaxiId() {
      java.lang.Object ref = taxiId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taxiId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string taxi_id = 1;</code>
     * @return The bytes for taxiId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaxiIdBytes() {
      java.lang.Object ref = taxiId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taxiId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIP_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tripId_ = "";
    /**
     * <code>required string trip_id = 2;</code>
     * @return Whether the tripId field is set.
     */
    @java.lang.Override
    public boolean hasTripId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string trip_id = 2;</code>
     * @return The tripId.
     */
    @java.lang.Override
    public java.lang.String getTripId() {
      java.lang.Object ref = tripId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tripId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string trip_id = 2;</code>
     * @return The bytes for tripId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTripIdBytes() {
      java.lang.Object ref = tripId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tripId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_ = 0D;
    /**
     * <code>required double latitude = 3;</code>
     * @return Whether the latitude field is set.
     */
    @java.lang.Override
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double latitude = 3;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private double longitude_ = 0D;
    /**
     * <code>required double longitude = 4;</code>
     * @return Whether the longitude field is set.
     */
    @java.lang.Override
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required double longitude = 4;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timestamp_ = 0L;
    /**
     * <code>required int64 timestamp = 7;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTaxiId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTripId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, taxiId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, tripId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(7, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, taxiId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tripId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.shazaei.protobuf.TaxiLoc.TaxiLocation)) {
        return super.equals(obj);
      }
      org.shazaei.protobuf.TaxiLoc.TaxiLocation other = (org.shazaei.protobuf.TaxiLoc.TaxiLocation) obj;

      if (hasTaxiId() != other.hasTaxiId()) return false;
      if (hasTaxiId()) {
        if (!getTaxiId()
            .equals(other.getTaxiId())) return false;
      }
      if (hasTripId() != other.hasTripId()) return false;
      if (hasTripId()) {
        if (!getTripId()
            .equals(other.getTripId())) return false;
      }
      if (hasLatitude() != other.hasLatitude()) return false;
      if (hasLatitude()) {
        if (java.lang.Double.doubleToLongBits(getLatitude())
            != java.lang.Double.doubleToLongBits(
                other.getLatitude())) return false;
      }
      if (hasLongitude() != other.hasLongitude()) return false;
      if (hasLongitude()) {
        if (java.lang.Double.doubleToLongBits(getLongitude())
            != java.lang.Double.doubleToLongBits(
                other.getLongitude())) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTaxiId()) {
        hash = (37 * hash) + TAXI_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTaxiId().hashCode();
      }
      if (hasTripId()) {
        hash = (37 * hash) + TRIP_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTripId().hashCode();
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.shazaei.protobuf.TaxiLoc.TaxiLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.TaxiLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.TaxiLocation)
        org.shazaei.protobuf.TaxiLoc.TaxiLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.shazaei.protobuf.TaxiLoc.internal_static_protobuf_TaxiLocation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.shazaei.protobuf.TaxiLoc.internal_static_protobuf_TaxiLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.shazaei.protobuf.TaxiLoc.TaxiLocation.class, org.shazaei.protobuf.TaxiLoc.TaxiLocation.Builder.class);
      }

      // Construct using org.shazaei.protobuf.TaxiLoc.TaxiLocation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        taxiId_ = "";
        tripId_ = "";
        latitude_ = 0D;
        longitude_ = 0D;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.shazaei.protobuf.TaxiLoc.internal_static_protobuf_TaxiLocation_descriptor;
      }

      @java.lang.Override
      public org.shazaei.protobuf.TaxiLoc.TaxiLocation getDefaultInstanceForType() {
        return org.shazaei.protobuf.TaxiLoc.TaxiLocation.getDefaultInstance();
      }

      @java.lang.Override
      public org.shazaei.protobuf.TaxiLoc.TaxiLocation build() {
        org.shazaei.protobuf.TaxiLoc.TaxiLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.shazaei.protobuf.TaxiLoc.TaxiLocation buildPartial() {
        org.shazaei.protobuf.TaxiLoc.TaxiLocation result = new org.shazaei.protobuf.TaxiLoc.TaxiLocation(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.shazaei.protobuf.TaxiLoc.TaxiLocation result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.taxiId_ = taxiId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tripId_ = tripId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.latitude_ = latitude_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.longitude_ = longitude_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.shazaei.protobuf.TaxiLoc.TaxiLocation) {
          return mergeFrom((org.shazaei.protobuf.TaxiLoc.TaxiLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.shazaei.protobuf.TaxiLoc.TaxiLocation other) {
        if (other == org.shazaei.protobuf.TaxiLoc.TaxiLocation.getDefaultInstance()) return this;
        if (other.hasTaxiId()) {
          taxiId_ = other.taxiId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasTripId()) {
          tripId_ = other.tripId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTaxiId()) {
          return false;
        }
        if (!hasTripId()) {
          return false;
        }
        if (!hasLatitude()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                taxiId_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                tripId_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 25: {
                latitude_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                longitude_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 56: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object taxiId_ = "";
      /**
       * <code>required string taxi_id = 1;</code>
       * @return Whether the taxiId field is set.
       */
      public boolean hasTaxiId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string taxi_id = 1;</code>
       * @return The taxiId.
       */
      public java.lang.String getTaxiId() {
        java.lang.Object ref = taxiId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taxiId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string taxi_id = 1;</code>
       * @return The bytes for taxiId.
       */
      public com.google.protobuf.ByteString
          getTaxiIdBytes() {
        java.lang.Object ref = taxiId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taxiId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string taxi_id = 1;</code>
       * @param value The taxiId to set.
       * @return This builder for chaining.
       */
      public Builder setTaxiId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        taxiId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string taxi_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaxiId() {
        taxiId_ = getDefaultInstance().getTaxiId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string taxi_id = 1;</code>
       * @param value The bytes for taxiId to set.
       * @return This builder for chaining.
       */
      public Builder setTaxiIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        taxiId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object tripId_ = "";
      /**
       * <code>required string trip_id = 2;</code>
       * @return Whether the tripId field is set.
       */
      public boolean hasTripId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string trip_id = 2;</code>
       * @return The tripId.
       */
      public java.lang.String getTripId() {
        java.lang.Object ref = tripId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tripId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string trip_id = 2;</code>
       * @return The bytes for tripId.
       */
      public com.google.protobuf.ByteString
          getTripIdBytes() {
        java.lang.Object ref = tripId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tripId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string trip_id = 2;</code>
       * @param value The tripId to set.
       * @return This builder for chaining.
       */
      public Builder setTripId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tripId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string trip_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTripId() {
        tripId_ = getDefaultInstance().getTripId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string trip_id = 2;</code>
       * @param value The bytes for tripId to set.
       * @return This builder for chaining.
       */
      public Builder setTripIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        tripId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>required double latitude = 3;</code>
       * @return Whether the latitude field is set.
       */
      @java.lang.Override
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double latitude = 3;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 3;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {

        latitude_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 4;</code>
       * @return Whether the longitude field is set.
       */
      @java.lang.Override
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required double longitude = 4;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 4;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {

        longitude_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 7;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int64 timestamp = 7;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 7;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.TaxiLocation)
    }

    // @@protoc_insertion_point(class_scope:protobuf.TaxiLocation)
    private static final org.shazaei.protobuf.TaxiLoc.TaxiLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.shazaei.protobuf.TaxiLoc.TaxiLocation();
    }

    public static org.shazaei.protobuf.TaxiLoc.TaxiLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaxiLocation>
        PARSER = new com.google.protobuf.AbstractParser<TaxiLocation>() {
      @java.lang.Override
      public TaxiLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TaxiLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaxiLocation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.shazaei.protobuf.TaxiLoc.TaxiLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_TaxiLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_TaxiLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!protobuf/proto/taxiLocation.proto\022\010pro" +
      "tobuf\"h\n\014TaxiLocation\022\017\n\007taxi_id\030\001 \002(\t\022\017" +
      "\n\007trip_id\030\002 \002(\t\022\020\n\010latitude\030\003 \002(\001\022\021\n\tlon" +
      "gitude\030\004 \002(\001\022\021\n\ttimestamp\030\007 \002(\003B\037\n\024org.s" +
      "hazaei.protobufB\007TaxiLoc"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_TaxiLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_TaxiLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_TaxiLocation_descriptor,
        new java.lang.String[] { "TaxiId", "TripId", "Latitude", "Longitude", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
