apiVersion: v2
name: device-rest
description: PathLens Device REST API (devices, locations)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: pathlens-common
    version: 0.1.0
    repository: "file://../pathlens-common"
